### ISSUE TITLE
Errors running ipfilter.sh on macOS

### ISSUE THREAD

**Issue by cyberjoost** [fonic/ipfilter#1]
Hi, I'm getting the following errors, on macOS:

./ipfilter.sh: line 33: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
(..)/ipfilter/ipfilter.conf: line 20: level1: unbound variable

**Comment by fonic** [comment]
That's the shell not being able to deal with `declare -A <var>` which is used to declare variables of type dict. I'd guess `bash --version` outputs something like `GNU bash, version 3.x.xx-release` on your system, correct? As stated in the README, Bash >= 4.0 is required for this script to work.

You can try upgrading Bash, e.g. by [following these instructions](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba).

I pushed commit fc064e3072bfc1411e902f4d1744eddf561ed2cf to make life easier for macOS users.

**Comment by fonic** [comment]
Have you had any success? I'd really like to know if it works on macOS.

**Comment by rcollie** [comment]
Running Bash 5. I get:

bash-5.0$ /Users/macmini/ipfilter/ipfilter.sh 

--== IP Filter Updater & Generator ==--

Creating temporary folder...
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
An error occured, aborting.

bash-5.0$

**Comment by fonic** [comment]
It would seem macOS doesn't like long options. Let me check this, I'll get back to you.

**Comment by fonic** [comment]
~~@rcollie: would you please download and test this version of `ipfilter.sh`: [link](https://gist.github.com/fonic/cfbbb44da5266fe51d6eb6bef7c85cf9)~~

@rcollie: I applied and committed all necessary changes for macOS. See 497237ddb16b68f73e598f058f06adc5395d882e.

Tested successfully on macOS Catalina 10.15.
I also added support for native notifications (option `-n`/`--notify`).

**Comment by SethWilliamson** [comment]
Same result as rcollie 

### Versions
- ipfilter.sh commit https://github.com/fonic/ipfilter/commit/497237ddb16b68f73e598f058f06adc5395d882e
- FreeNAS 11.2-STABLE
- Bash 4.4.19(0)-release

### Output
```bash
--== IP Filter Updater & Generator ==--

Creating temporary folder...
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
mktemp [-d] [-q] [-u] -t prefix
An error occured, aborting.
```

**Comment by fonic** [comment]
~~@SethWilliamson: try [this version](https://gist.github.com/fonic/2dd474acf28230f0c676c9d52e44ddd3). If it works, let me know what `echo $OSTYPE` outputs on your system.~~

@SethWilliamson: I applied and committed all necessary changes for FreeBSD. See 582bb12cf687a188cdd9235516b4752a90ff8b44.

Tested successfully on FreeNAS 11.2-U7.

**Comment by fonic** [comment]
@rcollie: Working for you now on macOS?
@SethWilliamson: Working for you now on FreeNAS?

**Comment by rcollie** [comment]
% ~/Downloads/ipfilter-497237ddb16b68f73e598f058f06adc5395d882e/ipfilter.sh
~/Downloads/ipfilter-497237ddb16b68f73e598f058f06adc5395d882e/ipfilter.sh: line 33: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

--== IP Filter Updater & Generator ==--

Creating temporary folder...
Downloading I-BlockList blocklists...
Downloading I-BlockList blocklist '0'...
Decompressing I-BlockList blocklists...
Decompressing I-BlockList blocklist '0'...
Merging I-BlockList blocklists...
~/Downloads/ipfilter-497237ddb16b68f73e598f058f06adc5395d882e/ipfilter.sh: line 326: readarray: command not found
An error occured, aborting.
Removing temporary folder...

**Comment by fonic** [comment]
@rcollie: please run using Bash again ;)

**Comment by fonic** [comment]
@rcollie: please run again using Bash 5 as you did before. You either used Zsh or macOS' outdated stock Bash this time.

**Comment by rcollie** [comment]
Sorry ran it on a different system running older bash. After installing wget it works like a champ. Well done sir.

**Comment by fonic** [comment]
@rcollie: great, my pleasure ;)

**Comment by fonic** [comment]
Closing this now as the matter is resolved for macOS. Created a separate issue for FreeBSD.
