### ISSUE TITLE
Add automatic GZip support

### ISSUE THREAD

**Issue by Tsuser1** [fonic/ipfilter#4]
I would like to request an option to automatically GZip the output of the script.

**Comment by fonic** [comment]
I think this would be a good addition. I'll look into it.

**Comment by fonic** [comment]
I currently don't have time to do this, as developing and testing for various supported platforms takes time. But, if you want to add support locally right away, simply edit the script, navigate to the very end and change
```
# Install final IP filter blocklist
print_hilite "Installing final IP filter blocklist..."
src="${tmpdir}/${FINAL_FILE}"
dst="${INSTALL_DST}"
cp "${src}" "${dst}"
```
to
```
# Install final IP filter blocklist
print_hilite "Installing final IP filter blocklist..."
src="${tmpdir}/${FINAL_FILE}"
dst="${INSTALL_DST}"
cp "${src}" "${dst}"
gzip "${dst}"
```
This will gzip the final installed file in-place.

**Comment by fonic** [comment]
I implemented the feature, allowing for gzip/bzip2/zip compression. Will be merged when tested successfully on all supported platforms within the next few days.

**Comment by fonic** [comment]
Done, see commit 85c6b0b2242cd8cc0627431e794163effb60c9a2 and [second release](https://github.com/fonic/ipfilter/releases/tag/ipfilter-v2.0).
